### ISSUE TITLE
Update to EAPI 8

### ISSUE THREAD

**Issue by ElDavoo** [positivelab/lab-overlay#2]
Hello,
some packages are not updated to EAPI 8 . Is it possible to update them?
Thank you!

**Comment by zaeb** [comment]
Hello,
If you mean [this bug](https://bugs.gentoo.org/913295), then it's fixed.

**Comment by ElDavoo** [comment]
> Hello, If you mean [this bug](https://bugs.gentoo.org/913295), then it's fixed.

yes, thanks.
